name: Daily Newsletter

on:
  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST

  workflow_dispatch:

jobs:
  run-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Pipeline
        run: |
          curl -X POST https://ai-newsletter-ebky.onrender.com/news/run-pipeline